/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import com.github.sarxos.webcam.WebcamResolution;
import com.google.zxing.BinaryBitmap;
import com.google.zxing.LuminanceSource;
import com.google.zxing.MultiFormatReader;
import com.google.zxing.NotFoundException;
import com.google.zxing.Result;
import com.google.zxing.client.j2se.BufferedImageLuminanceSource;
import com.google.zxing.common.HybridBinarizer;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.event.ItemEvent;
import java.awt.image.BufferedImage;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.ResolverStyle;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.concurrent.Executor;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.ScheduledFuture;
import java.util.concurrent.ThreadFactory;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author Arnold
 */
public class InternoMain extends javax.swing.JInternalFrame implements Runnable, ThreadFactory{
    String codigo, temporal_string; 
    int temporal_int, hora_i, hora_f, asistieron;
    ArrayList<String> codigoQR;
    ImageIcon imagen;
    private WebcamPanel panel = null;
    private Webcam webcam = null;
    private static final long serialVersionUID = 6441489157408381878L;
    private final Executor executor = Executors.newSingleThreadExecutor(this);
    final ScheduledExecutorService scheduler = Executors.newScheduledThreadPool(0);
    LocalDateTime locaDate = LocalDateTime.now();
    LocalDate fecha_hoy, fecha_general, inicio, fin;
    DateTimeFormatter formato;
    boolean clase_ac;
    
    int hours;
    int minutes;
    int seconds;
    String sent;
    ResultSet regreso;
    libreria_sql.Libreria_sql con;
    catedratico sesion;
    Login iniciador;
    Principal iniciado;
    Agg_seccion ventagregar_s;
    asignatura tempasign;
    depto tempdepto;
    seccion tempsecc;
    asuntosDeTiempo verificar;
    boolean as;
    Estudiante tempestud;
    ArrayList<asignatura> asigns;
    ArrayList<depto> deptos;
    ArrayList<seccion> seccs;
    ArrayList<Estudiante> estuds;
    ArrayList<Integer> dias_semana;
    Calendar Cl, CF;
    /**
     * Creates new form InternoMain
     * @param sesion
     * @param s
     * @param iniciador
     * @param iniciado
     */
    public InternoMain(catedratico sesion, Agg_seccion s, Login iniciador, Principal iniciado) {
        initComponents();
        this.con = new libreria_sql.Libreria_sql();
        imagen =new ImageIcon("C:\\Users\\Arnold\\Desktop\\U\\POO\\THREAD\\verde.jpg");
        codigoQR=new ArrayList();
        codigoQR.add("Arnold");
        this.sesion = sesion;
        this.iniciador = iniciador;
        this.iniciado = iniciado;
        jTextField7.setText(sesion.getNombre_cated());
        this.ventagregar_s = s;
        this.seccs = new ArrayList();
        this.asigns = new ArrayList();
        this.deptos = new ArrayList();
        fecha_hoy = LocalDate.now();
        formato= DateTimeFormatter.ofPattern("uuuu-MM-dd")
                .withResolverStyle(ResolverStyle.STRICT);
        verificar = new asuntosDeTiempo();
        Cl = new GregorianCalendar();
        Cl.setFirstDayOfWeek(Calendar.MONDAY);
        Cl.setMinimalDaysInFirstWeek( 4 );
        Cl.setTime(Date.valueOf(fecha_hoy));
        CF =new GregorianCalendar();
        CF.setFirstDayOfWeek(Calendar.MONDAY);
        CF.setMinimalDaysInFirstWeek( 4 );
        
        asistieron=0;
        jButton4.setEnabled(false);
        jButton5.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jTextField9 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        texto2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        texto = new javax.swing.JTextField();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Iniciar Clase");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(81, 152, 224));
        jLabel3.setText("Inicio de Clases");

        jLabel19.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(81, 152, 224));
        jLabel19.setText("Fecha Final");

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 11)); // NOI18N

        jTextField12.setEditable(false);
        jTextField12.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 11)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(81, 152, 224));
        jLabel5.setText("Asignatura: ");

        jLabel20.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(81, 152, 224));
        jLabel20.setText("(aaaa-mm-dd)");

        jLabel21.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(81, 152, 224));
        jLabel21.setText("(aaaa-mm-dd)");

        jLabel10.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(81, 152, 224));
        jLabel10.setText("Información de la Clase");

        jLabel6.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(81, 152, 224));
        jLabel6.setText("Sección: ");

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(81, 152, 224));
        jButton3.setText("Cerrar Sesión");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 11)); // NOI18N
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 11)); // NOI18N
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(81, 152, 224));
        jLabel15.setText("Mis Clases");

        jLabel7.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(81, 152, 224));
        jLabel7.setText("Hora Inicial");

        jTextField4.setEditable(false);
        jTextField4.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 11)); // NOI18N
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(81, 152, 224));
        jLabel16.setText("Hora Final");

        jLabel12.setFont(new java.awt.Font("Leelawadee UI Semilight", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(81, 152, 224));
        jLabel12.setText("Información del Catedrático");

        jLabel17.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(81, 152, 224));
        jLabel17.setText("Días");

        jLabel13.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(81, 152, 224));
        jLabel13.setText("Depto:");

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 11)); // NOI18N

        jTextField9.setEditable(false);
        jTextField9.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 11)); // NOI18N

        jTextField8.setEditable(false);
        jTextField8.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 11)); // NOI18N

        jTextField10.setEditable(false);
        jTextField10.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 11)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(81, 152, 224));
        jLabel9.setText("Catedrático: ");

        jLabel18.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(81, 152, 224));
        jLabel18.setText("U.V.");

        jTextField7.setEditable(false);
        jTextField7.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 11)); // NOI18N

        jTextField11.setEditable(false);
        jTextField11.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 11)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(81, 152, 224));
        jLabel2.setText("Estudiante: ");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(250, 250, 250));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(230, 230, 230)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 220, 170));
        jPanel1.add(texto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 220, -1));

        jLabel4.setText(" ");

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(81, 152, 224));
        jButton5.setText("Iniciar Clase");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(81, 152, 224));
        jLabel8.setText("Inasistencias: ");

        jLabel11.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(81, 152, 224));
        jLabel11.setText("Información del Estudiante");

        jTextField6.setEditable(false);
        jTextField6.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 11)); // NOI18N

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(81, 152, 224));
        jButton4.setText("Finalizar Clase");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(81, 152, 224));
        jLabel1.setText("Esperando Código QR...");

        jTextField1.setEditable(false);
        jTextField1.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 11)); // NOI18N

        texto.setFont(new java.awt.Font("Leelawadee UI Semilight", 0, 11)); // NOI18N
        texto.setBorder(null);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel4)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel8))
                                        .addGap(56, 56, 56)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextField6, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                                            .addComponent(jTextField1))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(texto, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)))
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(148, 148, 148))
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel13))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(28, 28, 28)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextField2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel20))
                            .addComponent(jTextField3)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel16))
                                .addGap(37, 37, 37)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField9)
                                    .addComponent(jTextField5)
                                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addGap(36, 36, 36))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addGap(77, 77, 77)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel21)
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jTextField10)
                                        .addGap(100, 100, 100))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75)
                                .addComponent(jLabel15))
                            .addComponent(jLabel10)
                            .addComponent(jButton3)
                            .addComponent(jLabel12))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addGap(62, 62, 62)
                                .addComponent(jButton4)
                                .addGap(484, 484, 484))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(134, 134, 134))))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12)
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel21))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(jLabel20)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(jLabel4)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(texto, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE))
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 849, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            //scheduler.shutdown();
            //System.out.println("Espere...");
            //scheduler.awaitTermination(5, TimeUnit.SECONDS);*/
            clase_ac = false;
            scheduler.awaitTermination(1, TimeUnit.SECONDS);
            cerrar_asistencia(tempasign.getCodigo_asig()+"-"+tempsecc.getNumseccion(),
                verificar.dia_letra(locaDate.getDayOfWeek().getValue()));
            if(asistieron == estuds.size()){
                JOptionPane.showMessageDialog(this,"Asistencia completa. Clase cerrada con éxito");
            }
            else{
                JOptionPane.showMessageDialog(this,"Clase cerrada con éxito.");
            }
            webcam.close();
            asistieron=0;
            jLabel4.setText(" ");
            texto.setText("");
            jTextField1.setText("");
            jTextField6.setText("");
            jButton3.setEnabled(true);
            jButton5.setEnabled(true);
            jComboBox1.setEnabled(true);
            jButton4.setEnabled(false);
        } catch (InterruptedException ex) {
            Logger.getLogger(InternoMain.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        locaDate = LocalDateTime.now();
        inicio = LocalDate.parse(jTextField2.getText(), formato);
        fin = LocalDate.parse(jTextField12.getText(), formato);
        hours = locaDate.getHour();
        hora_i = Integer.parseInt(jTextField5.getText());
        hora_f = Integer.parseInt(jTextField9.getText());
        if(String.valueOf(jComboBox1.getSelectedItem()).equals("Elija una Clase...")){
            JOptionPane.showMessageDialog(this, "Por favor seleccione una clase");
        }else if(fecha_hoy.isBefore(inicio)){
            JOptionPane.showMessageDialog(this, "Período de clase no iniciado");
        }else if(fecha_hoy.isAfter(fin)){
            JOptionPane.showMessageDialog(this, "Período de clase finalizado");
        }else if(hours != hora_i){
            JOptionPane.showMessageDialog(this, "Aún no es hora de la clase");
        }else if(verificar.siToca(tempsecc.getDias()) == false){
            JOptionPane.showMessageDialog(this, "Esta clase no se imparte hoy");
        }else if(verificar_run(fecha_hoy.getDayOfWeek().getValue()) == false){
            JOptionPane.showMessageDialog(this, "Esta clase ya se impartió hoy");
        }
        else{
            jButton4.setEnabled(true);
            jButton3.setEnabled(false);
            jButton5.setEnabled(false);
            jComboBox1.setEnabled(false);
            verificar_semana(tempsecc.getId_asig()+"-"+tempsecc.getNumseccion());
            añadir_estuds();
            jLabel4.setText(asistieron + " de " +estuds.size()+ " estudiantes presentes");
            initWebcam();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange() == ItemEvent.SELECTED){
            tempasign = new asignatura();
            tempsecc = new seccion();
            tempdepto = new depto();
            temporal_string = String.valueOf(jComboBox1.getSelectedItem());
            if(temporal_string.equals("Elija una Clase...")){
                jTextField2.setText("");
                jTextField3.setText("");
                jTextField4.setText("");
                jTextField5.setText("");
                jTextField8.setText("");
                jTextField9.setText("");
                jTextField10.setText("");
                jTextField11.setText("");
                jTextField12.setText("");
                jButton5.setEnabled(false);
            }
            else{
                jTextField3.setText(temporal_string.substring(6).trim());
                jTextField4.setText(temporal_string.substring(0, 4).trim());
                for(asignatura asign : asigns){
                    if(jTextField3.getText().equals(asign.getNombre_asig())){
                        tempasign = asign;
                        break;
                    }
                }
                temporal_int = tempasign.getId_depto();
                temporal_string = tempasign.getCodigo_asig();
                System.out.println(temporal_string);
                jTextField11.setText(String.valueOf(tempasign.getUv()));

                for(depto dpt : deptos){
                    if(temporal_int == dpt.getId_depto()){
                        tempdepto = dpt;
                        break;
                    }
                }
                jTextField8.setText(tempdepto.getNombre_depto());
                for(seccion secc : seccs){
                    if(secc.getNumseccion().equals(jTextField4.getText()) && temporal_string.equals(secc.getId_asig())){
                        tempsecc = secc;
                        break;
                    }
                }
                jTextField5.setText(String.valueOf(tempsecc.getHi()));
                jTextField9.setText(String.valueOf(tempsecc.getHf()));
                jTextField10.setText(tempsecc.getDias());
                jTextField2.setText(tempsecc.getFecha_i());
                jTextField12.setText(tempsecc.getFecha_f());
                jButton5.setEnabled(true);
            }
        }
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        iniciador.cerrarsesion();
        iniciado.dispose();
        iniciador.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed
    
    public void añadir_estuds(){
        estuds = new ArrayList();
        con.conectar();
        sent = "select cuenta, nombre_alumno, faltas from "
                + "["+tempasign.getCodigo_asig()+"-"+tempsecc.getNumseccion()+"]";
        regreso = con.seleccionar(sent);
        try {
            while(regreso.next()){
                tempestud = new Estudiante();
                tempestud.setCuenta_es(regreso.getString("cuenta"));
                tempestud.setNombre_es(regreso.getString("nombre_alumno"));
                tempestud.setFaltas(regreso.getInt("faltas"));
                estuds.add(tempestud);
            }
            System.out.println("Estudiantes añadidos");
        } catch (SQLException ex) {
            Logger.getLogger(InternoMain.class.getName()).log(Level.SEVERE, null, ex);
        } finally{
            con.cerrar();
        }
    }
    public boolean verificar_run(int dia){
        String dia_string = verificar.dia_letra(dia);
        try {
            con.conectar();
            sent = "select "+dia_string+" from ["+tempasign.getCodigo_asig()+"-"+tempsecc.getNumseccion()+"]";
            regreso = con.seleccionar(sent);
            if(regreso.next()){
                if(regreso.getString(1).equals("-")){
                    return true;
                }
            }
            return false;
        } catch (SQLException ex) {
            Logger.getLogger(InternoMain.class.getName()).log(Level.SEVERE, null, ex);
            return false;
        }finally{
            con.cerrar();
        }
    }
    public void cerrar_asistencia(String secc, String dia){
        for(int i=0; i<estuds.size();i++){
            if(estuds.get(i).getAsis_hoy().equals("-")){
                estuds.get(i).setAsis_hoy("N");
                estuds.get(i).setFaltas(estuds.get(i).getFaltas()+1);
            }
        }
        con.conectar();
        for(Estudiante estud : estuds){
            sent = "update ["+secc+"] set "+dia+" = '"+estud.getAsis_hoy()+"' ,"
                    + "faltas = "+estud.getFaltas()+" "
                    + "where cuenta = '"+estud.getCuenta_es()+"' ";
            con.insertar(sent);
        }
        con.cerrar();
    }
    public void verificar_semana(String secc){
        if(tempsecc.getSemana() != Cl.get(Calendar.WEEK_OF_YEAR) ){
            con.conectar();
            sent = "update ["+secc+"] set "
                    + "L = '-', "
                    + "Ma = '-', "
                    + "Mi = '-', "
                    + "J = '-', "
                    + "V = '-', "
                    + "S = '-', "
                    + "faltas = 0";
            con.insertar(sent);
            sent = "update seccion set semana = "+Calendar.WEEK_OF_YEAR+" where"
                    + "seccion = '"+tempsecc.getNumseccion()+"' and "
                    + "id_asig = '"+tempsecc.getId_asig()+"' ";
            con.cerrar();
        }
    }
    public void elim_secciones(){
        con.conectar();
        for(int i = 0; i<seccs.size(); i++){
            fecha_general = LocalDate.parse(seccs.get(i).getFecha_f(), formato);
            CF.setTime(Date.valueOf(fecha_general));
            if(Cl.get(Calendar.WEEK_OF_YEAR) - CF.get(Calendar.WEEK_OF_YEAR)   >= 2
                    && fecha_hoy.isAfter(fecha_general)){
                sent = "delete from seccion where seccion = '"+seccs.get(i).getNumseccion()+"' "
                        + "and id_asig = '"+seccs.get(i).getId_asig()+"'";
                con.insertar(sent);
                sent = "drop table ["+seccs.get(i).getId_asig()+"-"
                        +seccs.get(i).getNumseccion()+"]";
                con.insertar(sent);    
            }
        }
        con.cerrar();
    }
    private void initWebcam() {
        Dimension size = WebcamResolution.QVGA.getSize();
        webcam = Webcam.getWebcams().get(0); //0 is default webcam
        webcam.setViewSize(size);

        panel = new WebcamPanel(webcam);
        panel.setPreferredSize(size);
        panel.setFPSDisplayed(false);

        jPanel4.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 300));

        executor.execute(this);
    }
    
    @Override
    public void run() {
        asistieron = 0;
        clase_ac = true;
        as = false;
        System.out.println("Hecho");
        do {
            try {
                Thread.sleep(100);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }

            Result result = null;
            BufferedImage image = null;

            if (webcam.isOpen()) {
                if ((image = webcam.getImage()) == null) {
                    continue;
                }
            }
            LuminanceSource source = new BufferedImageLuminanceSource(image);
            BinaryBitmap bitmap = new BinaryBitmap(new HybridBinarizer(source));
            try {
                result = new MultiFormatReader().decode(bitmap);
            } catch (NotFoundException e) {
                //No result...
            }
            if (result != null) {
                texto.setText(result.getText());
                codigo=texto.getText();
                for(int i=0; i<estuds.size();i++){
                    if(codigo.equals(estuds.get(i).getCuenta_es())){
                        if(estuds.get(i).getAsis_hoy().equals("-")){
                            asistieron++;
                        }
                        estuds.get(i).setAsis_hoy("S");
                        jTextField1.setText(estuds.get(i).getNombre_es());
                        jTextField6.setText(String.valueOf(estuds.get(i).getFaltas()));
                        as = true;
                        jLabel4.setText(asistieron + " de " +estuds.size()+ " estudiantes presentes");
                    }
                }
                final ScheduledFuture<?> beepHandler = 
                    scheduler.scheduleAtFixedRate(new BeepTask(), 0, 3, TimeUnit.SECONDS);
                    scheduler.schedule(new Runnable() {
                    @Override
                    public void run() {
                        beepHandler.cancel(true);
                        jLabel1.setForeground(Color.BLACK);
                        jLabel1.setText("Esperando Código QR...");
                    }
                }, 3, TimeUnit.SECONDS);
            }
            System.out.println("esperando");
//???????????????????????????????????????????????????????????????????????????????????????????????

            if(hours==hora_f || asistieron == estuds.size()){
                System.out.println("Entra al if");
                jButton4.doClick();
            }
        } while (clase_ac);
        System.out.println("Detenido");
    }

    @Override
    public Thread newThread(Runnable r) {
       
        
        Thread t = new Thread(r, "My Thread");
        t.setDaemon(true);
        return t;
        
    }
    public class BeepTask implements Runnable {
      
        public void run() {
            if(as){
                jLabel1.setForeground(Color.GREEN);
                jLabel1.setText("Asistencia registrada");
                as = false;
            }else{
                jLabel1.setForeground(Color.RED);
                jLabel1.setText("Estudiante no encontrado");
            }
            System.out.println("Entró al beeptask");
            
      }
    }
    public void addSeccs(){
        seccs = new ArrayList();
        con.conectar();
        sent = "select * from seccion "/*+"where id_catedratico = '" + sesion.getId_cated() +"'"*/;
        regreso = con.seleccionar(sent);
        try {
            while(regreso.next()){
                tempsecc = new seccion();
                tempsecc.setNumseccion(regreso.getString("seccion"));
                tempsecc.setId_asig(regreso.getString("id_asig"));
                tempsecc.setId_catedratico(regreso.getInt("id_catedratico"));
                tempsecc.setHi(regreso.getInt("hi"));
                tempsecc.setHf(regreso.getInt("hf"));
                tempsecc.setFecha_i(regreso.getString("fecha_inicio"));
                tempsecc.setFecha_f(regreso.getString("fecha_fin"));
                tempsecc.setDias(regreso.getString("dias"));
                tempsecc.setFaltas_cated(regreso.getInt("faltas_cated"));
                tempsecc.setSemana(regreso.getInt("semana"));
                seccs.add(tempsecc);
            }
            System.out.println(seccs.size());
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } finally{
            con.cerrar();
        }
    }
    public void addDeptos(){
        deptos = new ArrayList();
        con.conectar();
        sent = "select depto.id_depto, nombre_depto from depto";
        regreso = con.seleccionar(sent);
        try {
            while(regreso.next()){
                tempdepto = new depto();
                tempdepto.setId_depto(regreso.getInt("id_depto"));
                tempdepto.setNombre_depto(regreso.getString("nombre_depto"));
                deptos.add(tempdepto);
            }
            System.out.println(deptos.size());
            System.out.println(deptos.get(0).getNombre_depto());
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } finally{
            con.cerrar();
        }
    }
    public void addAsigns(){
        asigns = new ArrayList();
        con.conectar();
        sent ="select codigo_asig, nombre_asig, id_depto, uv from asignatura "
/*+ "where catedratico.id_cated == '"+ sesion.getId_cated() +"'"*/;
        regreso = con.seleccionar(sent);
        try {
            while(regreso.next()){
            tempasign = new asignatura();
            tempasign.setCodigo_asig(regreso.getString("codigo_asig"));
            tempasign.setNombre_asig(regreso.getString("nombre_asig"));
            tempasign.setId_depto(regreso.getInt("id_depto"));
            tempasign.setUv(regreso.getInt("uv"));
            asigns.add(tempasign);
            }
            llenar_combo();
            System.out.println(asigns.size());
            System.out.println(asigns.get(0).getUv());
        } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } finally{
            con.cerrar();
        }
        
    }
    public void llenar_combo(){
        jComboBox1.removeAllItems();
        jComboBox1.addItem("Elija una Clase...");
        for (seccion secc : seccs) {
            for(asignatura asign : asigns){
                if(secc.getId_asig().equals(asign.getCodigo_asig()) && secc.getId_catedratico() == sesion.getId_cated()){
                   temporal_string = asign.getNombre_asig();
                   this.jComboBox1.addItem(secc.getNumseccion() + " - " + temporal_string);
                   break;
                }
            }   
        }
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField texto;
    private javax.swing.JTextField texto2;
    // End of variables declaration//GEN-END:variables
}
